[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "boto3>=1.37.38",
    "fastapi>=0.118.3",
    "mangum>=0.19.0",
    "openai>=2.2.0",
    "pypdf>=5.9.0",
    "python-dotenv>=1.0.1",
    "python-multipart>=0.0.20",
    "uvicorn>=0.33.0",
]
